media:
  - name: media
    label: Media
    input: src/media
    output: /media
    path: /media

content:
  - name: sermons
    label: Sermons
    type: collection
    path: src/collections/sermons
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date Preached
        type: date
      - name: series
        label: Sermon Series
        type: string # TODO: Add reference type
      - name: text
        label: Sermon Text
        type: string # TODO: Configure sermon text
      - name: preacher
        label: Preacher
        type: reference
        options:
          collection: preachers
          label: "{firstName} {lastName}"
          value: "{firstName {lastName}" # TODO: Should this be default of {path}?
          # search: "firstName, lastName"
          
      - name: spotifyURL
        label: Spotify URL
        type: string
      - name: googleDocsURL
        label: Google Docs URL
        type: string
      - name: body
        label: Notes
        type: text
  - name: preachers
    label: Preachers
    type: collection
    path: src/collections/preachers
    # filename:
    fields:
      - name: firstName
        label: First Name
        type: string
      - name: lastName
        label: Last Name
        type: string
      - name: guest
        label: Guest Preacher
        type: boolean
      - name: bio
        label: Bio
        type: text
      - name: image
        label: Upload a Picture
        type: image
    view:
      primary: firstName
