media:
  - name: media
    label: Media
    input: src/media
    output: /media
    path: /media

content:
  - name: sermons
    label: Sermons
    type: collection
    path: src/collections/sermons
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date Preached
        type: date
      - name: series
        label: Sermon Series
        type: string # TODO: Add reference type
      - name: text
        label: Sermon Text
        type: string # TODO: Configure sermon text
      - name: preacher
        label: Preacher
        type: string # TODO: Add reference tyype
      - name: spotifyURL
        label: Spotify URL
        type: string
      - name: googleDocsURL
        label: Google Docs URL
        type: string
      - name: body
        label: Notes
        type: text
