media:
  - name: media
    label: Media
    input: src/media
    output: /media
    path: /media
content:
  - name: sermons
    label: Sermons
    type: collection
    path: src/collections/sermons
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date Preached
        type: date
      - name: series
        label: Sermon Series
        type: reference
        options:
          collection: series
          label: "{title}"
      - name: text
        label: Sermon Text
        type: string # TODO: Configure sermon text
      - name: preacher
        label: Preacher
        type: reference
        options:
          collection: preachers
          # value: "{firstName} {lastName}" # TODO: Should this be default of {path}?
          # search: "firstName, lastName"
          label: "{firstName} {lastName}"
      - name: spotifyURL
        label: Spotify URL
        type: string
      - name: googleDocsURL
        label: Google Docs URL
        type: string
      - name: body
        label: Notes
        type: text
  - name: preachers
    label: Preachers
    type: collection
    path: src/collections/preachers
    fields:
      - name: name
        label: Name
        type: object
        fields:
          - name: firstName
            label: First Name
            type: string
          - name: lastName
            label: Last Name
            type: string
      - name: guest
        label: Guest Preacher
        type: boolean
      - name: bio
        label: Bio
        type: text
      - name: image
        label: Upload a Picture
        type: image
    view:
      primary: name
    filename: "{lastName}_{firstName}.md"
  - name: series
    label: Sermon Series
    type: collection
    path: src/collections/series
    filename: "{primary}.md"
    fields:
      - name: title
        label: "Series Title"
        type: string
      - name: image
        label: Upload a series image
        type: image
      - name: imageSquare
        label: Upload a square series image
        type: image
      - name: startDate
        label: Series start date
        type: date
      - name: book
        label: Bible Book(s)
        type: select
        options:
          multiple: true
          values:
            [
              "Genesis",
              "Exodus",
              "Leviticus",
              "Numbers",
              "Deuteronomy",
              "Joshua",
              "Judges",
              "Ruth",
              "1 Samuel",
              "2 Samuel",
              "1 Kings",
              "2 Kings",
              "1 Chronicles",
              "2 Chronicles",
              "Ezra",
              "Nehemiah",
              "Esther",
              "Job",
              "Psalms",
              "Proverbs",
              "Ecclesiastes",
              "Song of Solomon",
              "Isaiah",
              "Jeremiah",
              "Lamentations",
              "Ezekiel",
              "Daniel",
              "Hosea",
              "Joel",
              "Amos",
              "Obadiah",
              "Jonah",
              "Micah",
              "Nahum",
              "Habakkuk",
              "Zephaniah",
              "Haggai",
              "Zechariah",
              "Malachi",
              "Matthew",
              "Mark",
              "Luke",
              "John",
              "Acts",
              "Romans",
              "1 Corinthians",
              "2 Corinthians",
              "Galatians",
              "Ephesians",
              "Philippians",
              "Colossians",
              "1 Thessalonians",
              "2 Thessalonians",
              "1 Timothy",
              "2 Timothy",
              "Titus",
              "Philemon",
              "Hebrews",
              "James",
              "Jude",
              "Revelation",
            ]
